'use client';

import { useEffect, useState } from 'react';
import { AppShell } from '@/components/layout/AppShell';
import { MissionBrief, GraniteAssessment, Spacecraft, Anomaly, TelemetryReading } from '@/lib/types';
import { LoadingState, ErrorState, LoadingSpinner } from '@/components/ui/LoadingState';
import { StatusBadge, SeverityBadge } from '@/components/ui/Badge';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { HealthBar } from '@/components/ui/HealthBar';
import {
  Brain,
  RefreshCw,
  AlertTriangle,
  TrendingDown,
  TrendingUp,
  Minus,
  ChevronRight,
  Activity,
  Flag,
  CheckCircle,
  Radio,
  Zap,
  ShieldAlert,
  ListChecks,
} from 'lucide-react';
import {
  ResponsiveContainer,
  LineChart,
  Line,
  Tooltip,
} from 'recharts';
import { format } from 'date-fns';
import Link from 'next/link';

interface IntelligenceData {
  brief: MissionBrief;
  granite_assessment: GraniteAssessment | null;
  spacecraft: Spacecraft[];
  anomalies: Anomaly[];
  ai_provider: string;
  data_source: string;
}

// ── Granite Assessment card ────────────────────────────────────────────────

const STATUS_COLORS = {
  critical:    { ring: 'border-red-500/40',   bg: 'bg-red-400/8',    text: 'text-red-400',    badge: 'bg-red-400/10 border border-red-400/30 text-red-400' },
  warning:     { ring: 'border-amber-500/40', bg: 'bg-amber-400/8',  text: 'text-amber-400',  badge: 'bg-amber-400/10 border border-amber-400/30 text-amber-400' },
  nominal:     { ring: 'border-emerald-500/40', bg: 'bg-emerald-400/8', text: 'text-emerald-400', badge: 'bg-emerald-400/10 border border-emerald-400/30 text-emerald-400' },
  offline:     { ring: 'border-slate-500/40', bg: 'bg-slate-400/8',  text: 'text-slate-400',  badge: 'bg-slate-400/10 border border-slate-400/20 text-slate-400' },
  maintenance: { ring: 'border-blue-500/40',  bg: 'bg-blue-400/8',   text: 'text-blue-400',   badge: 'bg-blue-400/10 border border-blue-400/20 text-blue-400' },
} as const;

function GraniteAssessmentCard({ assessment }: { assessment: GraniteAssessment }) {
  const sc = STATUS_COLORS[assessment.overall_status] ?? STATUS_COLORS.nominal;
  const isGranite = assessment.provider === 'watsonx';

  const actionParts = assessment.recommended_action.split(':');
  const actionLabel = actionParts[0]?.trim() ?? 'ACTION';
  const actionBody  = actionParts.slice(1).join(':').trim() || assessment.recommended_action;

  const actionColor =
    actionLabel === 'IMMEDIATE' ? 'text-red-400 bg-red-400/10 border-red-400/20' :
    actionLabel === 'HIGH'      ? 'text-orange-400 bg-orange-400/10 border-orange-400/20' :
    actionLabel === 'MEDIUM'    ? 'text-amber-400 bg-amber-400/10 border-amber-400/20' :
                                  'text-slate-400 bg-[#111d35] border-[#2a3d5e]';

  return (
    <Card>
      <CardHeader
        title="Mission Assessment"
        subtitle={isGranite ? 'Generated by IBM Granite' : 'Generated by Demo AI'}
        icon={<Zap className="w-4 h-4 text-blue-400" />}
        actions={
          <div className={`flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-semibold border ${
            isGranite
              ? 'bg-emerald-400/10 border-emerald-400/30 text-emerald-400'
              : 'bg-amber-400/10 border-amber-400/30 text-amber-400'
          }`}>
            <Brain className="w-3 h-3" />
            {isGranite ? 'IBM Granite' : 'Demo AI'}
          </div>
        }
      />
      <CardBody className="space-y-4 pt-4 pb-4">
        {/* Status + confidence row */}
        <div className={`${sc.bg} ${sc.ring} border rounded-lg px-4 py-3 flex items-center justify-between`}>
          <div className="flex items-center gap-2">
            <span className={`w-2 h-2 rounded-full bg-current ${assessment.overall_status === 'critical' ? 'status-indicator-critical' : ''} ${sc.text}`} />
            <span className={`text-xs font-bold ${sc.text}`}>
              {assessment.overall_status.toUpperCase()}
            </span>
          </div>
          <div className="text-right">
            <div className="text-[9px] text-slate-500 uppercase tracking-wider">Confidence</div>
            <div className={`text-lg font-bold font-mono ${sc.text}`}>
              {(assessment.confidence * 100).toFixed(0)}%
            </div>
          </div>
        </div>

        {/* Primary risk */}
        <div>
          <div className="flex items-center gap-1.5 mb-1.5">
            <ShieldAlert className="w-3.5 h-3.5 text-red-400 flex-shrink-0" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Primary Risk</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">{assessment.primary_risk}</p>
        </div>

        {/* Evidence */}
        {assessment.evidence.length > 0 && (
          <div>
            <div className="flex items-center gap-1.5 mb-1.5">
              <ListChecks className="w-3.5 h-3.5 text-blue-400 flex-shrink-0" />
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Evidence</span>
            </div>
            <ul className="space-y-1">
              {assessment.evidence.map((e, i) => (
                <li key={i} className="flex gap-2 text-[11px] text-slate-400 leading-relaxed">
                  <span className="text-blue-500 flex-shrink-0 mt-px">▸</span>
                  <span>{e}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Recommended action */}
        <div className={`${actionColor} border rounded-lg p-3`}>
          <div className="text-[10px] font-bold uppercase tracking-wider mb-1">{actionLabel}</div>
          <div className="text-xs leading-relaxed">{actionBody}</div>
        </div>

        {/* Footer: generated timestamp */}
        <div className="text-[10px] text-slate-600 text-right">
          {new Date(assessment.generated_at).toUTCString()}
        </div>
      </CardBody>
    </Card>
  );
}

const SEVERITY_ORDER: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };

// ── Telemetry Trends helpers ───────────────────────────────────────────────

const TELEMETRY_METRICS = [
  { key: 'battery_voltage',       label: 'Battery Voltage',    unit: 'V',  color: '#3b82f6' },
  { key: 'temperature_internal',  label: 'Internal Temp',      unit: '°C', color: '#f97316' },
  { key: 'power_consumption',     label: 'Power Consumption',  unit: 'W',  color: '#a855f7' },
  { key: 'solar_panel_output',    label: 'Solar Panel Output', unit: 'W',  color: '#10b981' },
] as const;

type MetricKey = typeof TELEMETRY_METRICS[number]['key'];

/** Returns 'up', 'down', or 'stable' based on the last vs first quarter of readings. */
function getTrend(values: number[]): 'up' | 'down' | 'stable' {
  if (values.length < 4) return 'stable';
  const slice = Math.max(1, Math.floor(values.length / 4));
  const recent = values.slice(-slice).reduce((a, b) => a + b, 0) / slice;
  const old    = values.slice(0, slice).reduce((a, b) => a + b, 0) / slice;
  const delta  = (recent - old) / (Math.abs(old) || 1);
  if (delta >  0.01) return 'up';
  if (delta < -0.01) return 'down';
  return 'stable';
}

interface TelemetryTrendsProps {
  readings: TelemetryReading[];
  loading: boolean;
  error: string | null;
}

function TelemetryTrendsContent({ readings, loading, error }: TelemetryTrendsProps) {
  if (loading) {
    return (
      <div className="flex items-center justify-center py-10">
        <LoadingSpinner size="sm" />
        <span className="ml-2 text-xs text-slate-400">Loading telemetry…</span>
      </div>
    );
  }

  if (error) {
    return (
      <p className="text-xs text-red-400 text-center py-6">
        Failed to load telemetry: {error}
      </p>
    );
  }

  if (readings.length === 0) {
    return (
      <p className="text-xs text-slate-500 text-center py-6">
        No telemetry data available for ORBIT-01.
      </p>
    );
  }

  // Sample readings for sparklines (keep ≤30 points for performance)
  const step    = Math.max(1, Math.floor(readings.length / 30));
  const sampled = readings.filter((_, i) => i % step === 0);

  return (
    <div className="divide-y divide-[#1e2d4a]">
      {TELEMETRY_METRICS.map(({ key, label, unit, color }) => {
        const values  = sampled.map(r => r[key as MetricKey] as number);
        const latest  = readings[readings.length - 1][key as MetricKey] as number;
        const trend   = getTrend(values);
        const sparkData = sampled.map((r, i) => ({
          i,
          v: r[key as MetricKey] as number,
          t: format(new Date(r.timestamp), 'HH:mm'),
        }));

        const TrendIcon = trend === 'up' ? TrendingUp : trend === 'down' ? TrendingDown : Minus;
        const trendColor =
          trend === 'up'   ? 'text-emerald-400' :
          trend === 'down' ? 'text-red-400'     :
                             'text-slate-400';

        return (
          <div key={key} className="flex items-center gap-3 px-5 py-3">
            {/* Label + latest value */}
            <div className="w-44 flex-shrink-0">
              <div className="text-[11px] text-slate-400">{label}</div>
              <div className="text-sm font-mono font-semibold text-slate-200 mt-0.5">
                {latest.toFixed(1)}
                <span className="text-[10px] text-slate-500 ml-0.5">{unit}</span>
              </div>
            </div>

            {/* Sparkline */}
            <div className="flex-1 h-10 min-w-0">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={sparkData} margin={{ top: 2, right: 2, bottom: 2, left: 2 }}>
                  <Tooltip
                    content={({ active, payload }) => {
                      if (!active || !payload?.length) return null;
                      const pt = payload[0]?.payload as { v: number; t: string };
                      return (
                        <div className="bg-[#0f1a2e] border border-[#1e2d4a] rounded px-2 py-1 text-[10px]">
                          <span className="text-slate-400">{pt.t} — </span>
                          <span className="text-slate-100 font-mono">{pt.v.toFixed(2)}{unit}</span>
                        </div>
                      );
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="v"
                    stroke={color}
                    strokeWidth={1.5}
                    dot={false}
                    activeDot={{ r: 3, fill: color }}
                    isAnimationActive={false}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Trend indicator */}
            <div className={`flex items-center gap-1 flex-shrink-0 ${trendColor}`}>
              <TrendIcon className="w-3.5 h-3.5" />
              <span className="text-[10px] font-medium capitalize">{trend}</span>
            </div>
          </div>
        );
      })}

      {/* Timestamp */}
      <div className="px-5 py-2">
        <span className="text-[10px] text-slate-600">
          ORBIT-01 · last 6 h · {readings.length} readings
        </span>
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────

export default function MissionIntelligencePage() {
  const [data, setData] = useState<IntelligenceData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Telemetry state
  const [telemetryReadings, setTelemetryReadings] = useState<TelemetryReading[]>([]);
  const [telemetryLoading, setTelemetryLoading] = useState(true);
  const [telemetryError, setTelemetryError] = useState<string | null>(null);

  const fetchTelemetry = async () => {
    setTelemetryLoading(true);
    setTelemetryError(null);
    try {
      const res = await fetch('/api/telemetry?spacecraft_id=ORBIT-01&hours=6');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setTelemetryReadings(json.telemetry ?? []);
    } catch (err) {
      setTelemetryError(err instanceof Error ? err.message : 'Telemetry unavailable');
    } finally {
      setTelemetryLoading(false);
    }
  };

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/mission-intelligence');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setData(json);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load intelligence');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    fetchTelemetry();
  }, []);

  if (loading) return (
    <AppShell title="Mission Intelligence" subtitle="AI-generated mission briefing">
      <LoadingState message="Generating mission intelligence..." />
    </AppShell>
  );

  if (error || !data) return (
    <AppShell title="Mission Intelligence">
      <ErrorState message={error || 'Data unavailable'} onRetry={fetchData} />
    </AppShell>
  );

  const { brief, granite_assessment, spacecraft, anomalies } = data;
  const criticalAnomalies = anomalies.filter(a => a.severity === 'critical' || a.severity === 'high')
    .sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);

  const statusColors = {
    critical: { bg: 'bg-red-400/5 border-red-500/30', text: 'text-red-400', badge: 'bg-red-400/10 border border-red-400/30 text-red-400' },
    warning: { bg: 'bg-amber-400/5 border-amber-500/30', text: 'text-amber-400', badge: 'bg-amber-400/10 border border-amber-400/30 text-amber-400' },
    nominal: { bg: 'bg-emerald-400/5 border-emerald-500/30', text: 'text-emerald-400', badge: 'bg-emerald-400/10 border border-emerald-400/30 text-emerald-400' },
    offline: { bg: 'bg-slate-400/5 border-slate-500/30', text: 'text-slate-400', badge: '' },
    maintenance: { bg: 'bg-blue-400/5 border-blue-500/30', text: 'text-blue-400', badge: '' },
  };
  const sc = statusColors[brief.overall_status] || statusColors.nominal;

  return (
    <AppShell
      title="Mission Intelligence"
      subtitle={`Generated at ${new Date(brief.generated_at).toUTCString()}`}
      dataSource={data.data_source as any}
    >
      {/* Header with overall status */}
      <div className={`${sc.bg} border rounded-xl p-5 mb-5 flex items-start justify-between`}>
        <div>
          <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold ${sc.badge} mb-3`}>
            <span className={`w-2 h-2 rounded-full bg-current ${brief.overall_status === 'critical' ? 'status-indicator-critical' : ''}`} />
            MISSION STATUS: {brief.overall_status.toUpperCase()}
          </div>
          <p className="text-sm text-slate-300 max-w-3xl leading-relaxed">{brief.summary}</p>
        </div>
        <div className="flex items-center gap-3 flex-shrink-0 ml-4">
          <div className="text-right">
            <div className="text-[10px] text-slate-500 uppercase tracking-wider">AI Confidence</div>
            <div className="text-2xl font-bold font-mono text-blue-400">{(brief.confidence * 100).toFixed(0)}%</div>
          </div>
          <button
            onClick={fetchData}
            className="p-2.5 rounded-lg bg-[#0f1a2e] border border-[#1e2d4a] text-slate-400 hover:text-slate-200 hover:bg-[#111d35] transition-colors"
            title="Regenerate briefing"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-5">
        {/* Left column */}
        <div className="xl:col-span-2 space-y-5">
          {/* Critical issues */}
          {brief.critical_issues.length > 0 && (
            <Card>
              <CardHeader
                title="Critical Issues"
                subtitle={`${brief.critical_issues.length} requiring immediate attention`}
                icon={<AlertTriangle className="w-4 h-4 text-red-400" />}
              />
              <div className="divide-y divide-[#1e2d4a]">
                {brief.critical_issues.map((issue, i) => (
                  <div key={i} className="p-4 flex gap-3">
                    <div className="w-6 h-6 rounded-full bg-red-400/10 border border-red-400/30 flex items-center justify-center flex-shrink-0 mt-0.5 text-[11px] text-red-400 font-bold">
                      {i + 1}
                    </div>
                    <div className="text-xs text-slate-300 leading-relaxed flex-1">{issue}</div>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* Investigation priorities */}
          {brief.spacecraft_requiring_attention.length > 0 && (
            <Card>
              <CardHeader
                title="Investigation Priorities"
                subtitle="Sorted by urgency"
                icon={<Flag className="w-4 h-4 text-orange-400" />}
              />
              <div className="divide-y divide-[#1e2d4a]">
                {brief.spacecraft_requiring_attention.map(item => {
                  const sc = spacecraft.find(s => s.id === item.spacecraft_id);
                  return (
                    <Link
                      key={item.spacecraft_id}
                      href={`/satellites/${item.spacecraft_id}`}
                      className="flex items-center gap-4 p-4 hover:bg-[#111d35] transition-colors group"
                    >
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold flex-shrink-0 ${
                        item.priority === 1
                          ? 'bg-red-400/15 text-red-400 border border-red-400/30'
                          : item.priority === 2
                          ? 'bg-orange-400/15 text-orange-400 border border-orange-400/30'
                          : 'bg-amber-400/15 text-amber-400 border border-amber-400/30'
                      }`}>
                        {item.priority}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-sm font-mono font-bold text-slate-200 group-hover:text-blue-300 transition-colors">
                            {item.spacecraft_name}
                          </span>
                          {sc && <StatusBadge status={sc.status} />}
                        </div>
                        <div className="text-xs text-slate-400">{item.reason}</div>
                        {sc && (
                          <div className="mt-1.5">
                            <HealthBar score={sc.health_score} showValue size="sm" />
                          </div>
                        )}
                      </div>
                      <ChevronRight className="w-4 h-4 text-slate-600 group-hover:text-slate-300 transition-colors flex-shrink-0" />
                    </Link>
                  );
                })}
              </div>
            </Card>
          )}

          {/* Telemetry trends */}
          <Card>
            <CardHeader
              title="Telemetry Trends"
              subtitle="ORBIT-01 · last 6 hours"
              icon={<Activity className="w-4 h-4 text-blue-400" />}
            />
            <TelemetryTrendsContent
              readings={telemetryReadings}
              loading={telemetryLoading}
              error={telemetryError}
            />
          </Card>
        </div>

        {/* Right column */}
        <div className="space-y-5">
          {/* Granite Assessment */}
          {granite_assessment && (
            <GraniteAssessmentCard assessment={granite_assessment} />
          )}

          {/* Recommended actions */}
          <Card>
            <CardHeader
              title="Recommended Actions"
              subtitle="Prioritized response plan"
              icon={<CheckCircle className="w-4 h-4 text-emerald-400" />}
            />
            <CardBody className="space-y-3">
              {brief.recommended_actions.map((action, i) => {
                const isImmediate = action.startsWith('IMMEDIATE');
                const isHigh = action.startsWith('HIGH');
                const isMedium = action.startsWith('MEDIUM');
                const color = isImmediate ? 'text-red-400 bg-red-400/10 border-red-400/20'
                  : isHigh ? 'text-orange-400 bg-orange-400/10 border-orange-400/20'
                  : isMedium ? 'text-amber-400 bg-amber-400/10 border-amber-400/20'
                  : 'text-slate-400 bg-[#111d35] border-[#2a3d5e]';

                const parts = action.split(':');
                const label = parts[0]?.trim() || `ACTION ${i + 1}`;
                const description = parts.slice(1).join(':').trim() || action;

                return (
                  <div key={i} className={`${color} border rounded-lg p-3`}>
                    <div className="text-[10px] font-bold uppercase tracking-wider mb-1">{label}</div>
                    <div className="text-xs leading-relaxed">{description}</div>
                  </div>
                );
              })}
            </CardBody>
          </Card>

          {/* Active anomalies summary */}
          {criticalAnomalies.length > 0 && (
            <Card>
              <CardHeader
                title="Critical Anomalies"
                subtitle={`${criticalAnomalies.length} high-severity`}
                icon={<Radio className="w-4 h-4 text-red-400" />}
              />
              <div className="divide-y divide-[#1e2d4a]">
                {criticalAnomalies.slice(0, 4).map(anomaly => (
                  <div key={anomaly.id} className="p-3 space-y-1.5">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-mono text-slate-300">{anomaly.spacecraft_name}</span>
                      <SeverityBadge severity={anomaly.severity} />
                    </div>
                    <div className="text-[11px] text-slate-400 leading-relaxed">
                      {anomaly.explanation.slice(0, 130)}...
                    </div>
                  </div>
                ))}
              </div>
              <div className="p-3 border-t border-[#1e2d4a]">
                <Link
                  href="/anomalies"
                  className="flex items-center justify-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 transition-colors"
                >
                  View all anomalies <ChevronRight className="w-3 h-3" />
                </Link>
              </div>
            </Card>
          )}

          {/* AI source */}
          <div className="bg-[#0f1a2e] border border-[#1e2d4a] rounded-xl p-4">
            <div className="flex items-center gap-2 mb-2">
              <Brain className="w-4 h-4 text-blue-400" />
              <span className="text-xs font-medium text-slate-300">Intelligence Source</span>
            </div>
            <div className="space-y-1.5 text-[11px]">
              <div className="flex justify-between">
                <span className="text-slate-500">AI Engine</span>
                <span className={data.ai_provider === 'watsonx' ? 'text-emerald-400' : 'text-amber-400'}>
                  {data.ai_provider === 'watsonx' ? 'IBM Granite' : 'Demo AI'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Data Source</span>
                <span className="text-blue-400">{data.data_source === 'simulated' ? 'Simulation' : 'Live'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-500">Analysis Basis</span>
                <span className="text-slate-300">{spacecraft.length} spacecraft</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
