// ============================================================
// Core type definitions for OrbitGuard AI
// ============================================================

export type SpacecraftStatus = 'nominal' | 'warning' | 'critical' | 'offline' | 'maintenance';
export type AnomalySeverity = 'low' | 'medium' | 'high' | 'critical';
export type AnomalyType =
  | 'power_system'
  | 'thermal'
  | 'communications'
  | 'orbit_deviation'
  | 'attitude_control'
  | 'propulsion'
  | 'payload'
  | 'data_handling'
  | 'unknown';

export type TelemetryParameter =
  | 'battery_voltage'
  | 'power_consumption'
  | 'temperature_internal'
  | 'temperature_external'
  | 'signal_strength'
  | 'altitude'
  | 'velocity'
  | 'solar_panel_output'
  | 'attitude_error'
  | 'memory_usage';

export interface Spacecraft {
  id: string;
  name: string;
  mission: string;
  launch_date: string;
  operator: string;
  orbit_type: string;
  status: SpacecraftStatus;
  health_score: number;
  risk_level: 'low' | 'medium' | 'high' | 'critical';
  last_telemetry_at: string;
  active_anomalies: number;
  description: string;
  subsystems: SubsystemHealth[];
  norad_id?: number;
}

export interface SubsystemHealth {
  name: string;
  score: number;
  status: SpacecraftStatus;
  last_updated: string;
  details?: string;
}

export interface TelemetryReading {
  id: string;
  spacecraft_id: string;
  timestamp: string;
  battery_voltage: number;       // Volts (nominal: 27-29V)
  power_consumption: number;     // Watts
  temperature_internal: number;  // °C
  temperature_external: number;  // °C
  signal_strength: number;       // dBm (-120 to -60)
  altitude: number;              // km
  velocity: number;              // km/s
  solar_panel_output: number;    // Watts
  attitude_error: number;        // degrees
  memory_usage: number;          // percentage 0-100
}

export interface Anomaly {
  id: string;
  spacecraft_id: string;
  spacecraft_name: string;
  anomaly_type: AnomalyType;
  severity: AnomalySeverity;
  parameter: TelemetryParameter;
  observed_value: number;
  expected_range: [number, number];
  confidence: number;            // 0-1
  timestamp: string;
  resolved_at?: string;
  explanation: string;
  recommended_action: string;
  related_parameters?: TelemetryParameter[];
  is_active: boolean;
}

export interface MissionBrief {
  generated_at: string;
  overall_status: SpacecraftStatus;
  summary: string;
  critical_issues: string[];
  spacecraft_requiring_attention: Array<{
    spacecraft_id: string;
    spacecraft_name: string;
    reason: string;
    priority: number;
  }>;
  telemetry_trends: string[];
  recommended_actions: string[];
  confidence: number;
  data_source: 'watsonx' | 'demo';
}

/**
 * Structured per-mission AI assessment generated by IBM Granite.
 * Returned alongside the MissionBrief so the UI can render a dedicated card.
 * Never contains credentials or internal server details.
 */
export interface GraniteAssessment {
  /** ISO timestamp when this assessment was generated */
  generated_at: string;
  /** 'watsonx' when produced by IBM Granite, 'demo' when using the deterministic fallback */
  provider: 'watsonx' | 'demo';
  /** Overall mission status determined by Granite */
  overall_status: SpacecraftStatus;
  /** Primary operational risk in one to two sentences */
  primary_risk: string;
  /** Supporting evidence: specific telemetry values and anomaly readings cited by Granite */
  evidence: string[];
  /** Single most important recommended next action, prefixed with IMMEDIATE/HIGH/MEDIUM/MONITOR */
  recommended_action: string;
  /** AI confidence 0–1 */
  confidence: number;
}

/** Five-section structured operational analysis returned by the Copilot. */
export interface CopilotAnalysis {
  situation: string;       // What is happening — grounded in telemetry facts
  evidence: string[];      // Specific observed values and anomaly readings used
  risk: string;            // Operational risk and potential impact
  next_step: string;       // Single most important recommended action
  confidence: number;      // 0-1 AI confidence in this analysis
}

export interface AIChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  context?: {
    spacecraft_ids?: string[];
    anomaly_ids?: string[];
    telemetry_snapshot?: Partial<TelemetryReading>;
  };
  metadata?: {
    confidence?: number;
    data_source?: 'watsonx' | 'demo';
    reasoning?: string;
    /** Structured analysis sections, present when the response was parsed successfully */
    structured?: CopilotAnalysis;
    /** Data sources that fed the AI response */
    sources?: string[];
  };
}

export interface HealthScoreBreakdown {
  overall: number;
  battery: number;
  thermal: number;
  communications: number;
  orbit: number;
  power: number;
  attitude: number;
}

export interface DashboardMetrics {
  active_spacecraft: number;
  healthy_spacecraft: number;
  warning_spacecraft: number;
  critical_spacecraft: number;
  offline_spacecraft: number;
  open_anomalies: number;
  resolved_anomalies_24h: number;
  total_telemetry_readings_24h: number;
  data_source: DataSourceMode;
  last_updated: string;
}

/**
 * Describes where the orbital / fleet data came from.
 *   simulated — static reference values from orbital-simulation.ts (no external call)
 *   n2yo      — real-time positions from the N2YO API (ORBITAL_DATA_MODE=live)
 *   fallback  — live mode was requested but the N2YO call failed; simulation used instead
 *   live      — alias retained for dashboard/telemetry pipeline compatibility
 */
export type DataSourceMode = 'live' | 'simulated' | 'n2yo' | 'fallback' | 'mixed' | 'iss-live';

export interface SpaceDataProviderState {
  isLoading: boolean;
  error: string | null;
  dataSource: DataSourceMode;
  lastUpdated: string | null;
}

// ── Orbital / N2YO position data ──────────────────────────────────────────────

/**
 * Real-time orbital position for a tracked object.
 * Sourced from N2YO when live mode is active; not derived from simulated telemetry.
 */
export interface OrbitalPosition {
  /** NORAD catalog number */
  norad_id: number;
  /** Satellite/object name from TLE database */
  name: string;
  /** Latitude in decimal degrees (-90 to +90) */
  latitude: number;
  /** Longitude in decimal degrees (-180 to +180) */
  longitude: number;
  /** Altitude above mean sea level (km) */
  altitude_km: number;
  /** Ground-track velocity (km/s) */
  velocity_km_s: number;
  /** Timestamp of this position fix (ISO 8601) */
  timestamp: string;
  /** Visibility category: 'daylight' | 'eclipsed' | 'visible' | 'unknown' */
  visibility: 'daylight' | 'eclipsed' | 'visible' | 'unknown';
  /** Inclination of the orbit (degrees) */
  inclination_deg?: number;
  /** Orbital period (minutes) */
  period_min?: number;
  /** Number of revolutions since epoch */
  revs_at_epoch?: number;
  /** True if position was read from live N2YO API */
  is_live: boolean;
}

/** Top-level response shape returned by /api/orbital */
export interface OrbitalDataResponse {
  positions: OrbitalPosition[];
  data_source: DataSourceMode;
  /** ISO timestamp of the most recent API fetch */
  fetched_at: string;
  /** Human-readable note, e.g. fallback reason */
  note?: string;
  error?: string;
}

export interface AnomalyDetectionResult {
  anomaly_type: AnomalyType;
  severity: AnomalySeverity;
  parameter: TelemetryParameter;
  observed_value: number;
  expected_range: [number, number];
  confidence: number;
  timestamp: string;
  explanation: string;
  recommended_action: string;
  related_parameters?: TelemetryParameter[];
}

export interface VectorSearchResult {
  id: string;
  content: string;
  metadata: {
    source: string;
    document_type: 'manual' | 'procedure' | 'documentation' | 'emergency' | 'interpretation';
    spacecraft_id?: string;
    relevance_score: number;
  };
}

export interface TimeRange {
  label: string;
  value: '1h' | '6h' | '24h' | '7d';
  hours: number;
}

export const TIME_RANGES: TimeRange[] = [
  { label: '1H', value: '1h', hours: 1 },
  { label: '6H', value: '6h', hours: 6 },
  { label: '24H', value: '24h', hours: 24 },
  { label: '7D', value: '7d', hours: 168 },
];
